import React, { useMemo } from 'react';
import { useProject } from '../store/ProjectContext';
import { calculateTotalPower, calculateTotalWeight, validateProject } from '../utils/calculations';

export function PlanningPanel(){
  const { project, dispatch } = useProject();
  const power=useMemo(()=>calculateTotalPower(project.objects),[project.objects]);
  const weight=useMemo(()=>calculateTotalWeight(project.objects),[project.objects]);
  const dmxConflicts=useMemo(()=>{
    const seen=new Set<string>(), out:string[]=[];
    for(const f of project.lighting||[]) for(let ch=0;ch<f.channels;ch++){ const k=`${f.universe}:${f.address+ch}`; if(seen.has(k)) out.push(`DMX conflict: U${f.universe} address ${f.address+ch}`); seen.add(k); }
    return [...new Set(out)];
  },[project.lighting]);
  const addLight=()=>dispatch({type:'ADD_LIGHTING',payload:{id:crypto.randomUUID(),brand:'',model:'',type:'Moving Head',mode:'Standard',universe:1,address:1,channels:16,quantity:1,position:''}});
  const addCircuit=()=>dispatch({type:'ADD_CIRCUIT',payload:{id:crypto.randomUUID(),name:`Circuit ${(project.circuits||[]).length+1}`,voltage:230,capacityA:16,phase:'L1',objectIds:[]}});
  return <div style={{overflowY:'auto',height:'100%',paddingBottom:24}}>
    <div className="sheet-header"><strong>Planning & Engineering Tools</strong></div>
    <div className="card"><h3>Power</h3><p>Total: <strong>{power.totalWatts.toLocaleString()} W</strong> · {power.estimatedAmps230V.toFixed(1)} A @230V</p><p style={{fontSize:'.75rem',color:'var(--warning)'}}>Planning estimate only. Circuit protection, diversity, phase balance and cable selection require qualified electrical design.</p>{(project.circuits||[]).map(c=>{const load=c.objectIds.reduce((s,id)=>s+(project.objects.find(o=>o.id===id)?.powerWatts||0),0);const amps=load/(c.voltage||230);return <div className="card" key={c.id}><div style={{display:'flex',gap:6}}><input value={c.name} onChange={e=>dispatch({type:'UPDATE_CIRCUIT',payload:{id:c.id,changes:{name:e.target.value}}})}/><button className="btn btn-ghost" onClick={()=>dispatch({type:'DELETE_CIRCUIT',payload:c.id})}>×</button></div><p>{load} W · {amps.toFixed(1)} A / {c.capacityA} A · {c.voltage} V · {c.phase}</p><select multiple style={{width:'100%',minHeight:80}} value={c.objectIds} onChange={e=>dispatch({type:'UPDATE_CIRCUIT',payload:{id:c.id,changes:{objectIds:Array.from(e.target.selectedOptions).map(o=>o.value)}}})}>{project.objects.filter(o=>(o.powerWatts||0)>0).map(o=><option key={o.id} value={o.id}>{o.name} · {o.powerWatts}W</option>)}</select>{amps>c.capacityA&&<div className="warning-box">Circuit overload warning.</div>}</div>})}<button className="btn btn-primary" onClick={addCircuit}>Add circuit</button></div>
    <div className="card"><h3>Lighting / DMX Patch</h3><button className="btn btn-primary" onClick={addLight}>Add fixture</button>{(project.lighting||[]).map(f=><div className="card" key={f.id}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><input placeholder="Brand" value={f.brand} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{brand:e.target.value}}})}/><input placeholder="Model" value={f.model} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{model:e.target.value}}})}/><input placeholder="Type" value={f.type} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{type:e.target.value}}})}/><input placeholder="Mode" value={f.mode} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{mode:e.target.value}}})}/><input type="number" min="1" max="64" value={f.universe} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{universe:+e.target.value}}})}/><input type="number" min="1" max="512" value={f.address} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{address:+e.target.value}}})}/><input type="number" min="1" max="512" value={f.channels} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{channels:+e.target.value}}})}/><input type="number" min="1" value={f.quantity} onChange={e=>dispatch({type:'UPDATE_LIGHTING',payload:{id:f.id,changes:{quantity:+e.target.value}}})}/></div><button className="btn btn-ghost" onClick={()=>dispatch({type:'DELETE_LIGHTING',payload:f.id})}>Delete fixture</button></div>)}{dmxConflicts.map(x=><div className="warning-box" key={x}>{x}</div>)}</div>
    <div className="card"><h3>Rigging / Load</h3><p>Estimated total equipment mass: <strong>{weight.totalKg.toFixed(1)} kg</strong></p><p style={{fontSize:'.75rem',color:'var(--warning)'}}>Planning estimate only. Suspended loads, anchor points, truss, motors and venue structures require certified rigging calculations and inspection.</p></div>
    <div className="card"><h3>Project validation</h3>{validateProject(project).length?validateProject(project).map((x,i)=><div key={i} className="warning-box">{x}</div>):<p>✓ No basic validation issues detected.</p>}</div>
  </div>
}
