Run if [ ! -f "android/app/build.gradle" ]; then
No native Android project found yet -- creating it.
[error] android platform already exists.
        To re-add this platform, first remove ./android, then run this command again.
        WARNING: Your native project will be completely removed.
Error: Process completed with exit code 1.
